### ISSUE TITLE
无法确定浏览器版本

### ISSUE THREAD

**Issue by Muggles001** [y-tai/zodgame_checkin#35]
![image](https://github.com/user-attachments/assets/33691f64-ce47-4863-ab0a-73385936950d)
如图，cookie是新抓的

**Comment by y-tai** [comment]
第四行这个应该只是warning，可能是因为没过得去cloudflare导致运行失败了

**Comment by CirnoSalt** [comment]
zod这几天开了cloudflare质询，脚本应该是过不了人机验证的

**Comment by y-tai** [comment]
不过按照[undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver)这个库的说法，过不去cloudflare可能是因为请求是从github的datacenter发出的，本地的话或许没有问题，不过我并没有测试过。
当初使用这个库就是为了利用脚本过cloudflare的，不过现在也不是特别好使了

**Comment by Muggles001** [comment]
唉，那看来最近没法跑了

**Comment by livinghub** [comment]
> 不过按照[undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver)这个库的说法，过不去cloudflare可能是因为请求是从github的datacenter发出的，本地的话或许没有问题，不过我并没有测试过。 当初使用这个库就是为了利用脚本过cloudflare的，不过现在也不是特别好使了

试了本地运行，cf验证也过不去

**Comment by y-tai** [comment]
由于zodgame放宽了验证，这个问题已不会出现。
本人同时也在探寻其他绕过cloudflare的方法，感谢大家的支持。
